channels:
- conda-forge
dependencies:
- python=3.9.0
- pip<=20.2.3
- pip:
  - mlflow==2.16.0
  - cloudpickle==3.0.0
  - numpy==2.0.2
  - psutil==6.0.0
  - scikit-learn==1.5.1
  - scipy==1.13.1
name: mlflow-env
