stages:
  load_data:
    cmd: python get_data.py --config=params.yaml
    deps:
    - get_data.py
    outs:
    - data/processed_data.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - data/raw/raw_Data.csv    # Corrected path
    - src/split_data.py
    outs:
    - data/processed/train.csv
    - data/processed/test.csv

  train_and_eval:
    cmd: python src/train_and_eval.py --config=params.yaml
    deps:
    - src/train_and_eval.py
    - data/processed/train.csv
    - data/processed/test.cscv
    params:
    - Algorithm.LogisticRegression.parameters.penalty
    - Algorithm.LogisticRegression.parameters.C
    - Algorithm.LogisticRegression.parameters.solver
    - Algorithm.LogisticRegression.parameters.max_iter
    metrics:
    - reports/params.json:
        cache: false
    - reports/scores.json:
        cache: false

  log_production_model:
    cmd: python src/log_production.py --config=params.yaml
    deps:
    - src/log_production.py
