base:
  project_name : Diabetes prediction using mlops
  random_state : 42
  target_column : Outcome

data_source :
  source_Data_location : source_data/pima_indian.csv

load_data :
  load_Data_location : data/raw/raw_Data.csv

split_data :
  train_Data_location : data/processed/train.csv
  test_Data_location : data/processed/test.csv
  test_size : 0.2

Algorithm:
  LogisticRegression:
    parameters:
      penalty: 'l1'           # Common choice for regularization
      C: 10                 # Default value, can be adjusted based on model performance
      solver: 'saga'         # Suitable for small to medium-sized datasets
      max_iter: 75          # Increase if the model is not converging

model_path : models

MLflow_config:
  remote_server_uri: 'https://dagshub.com/mohammednihal9986/Mohdnihal03-Diabetes-Prediction-with-Mlops.mlflow'
  storage_location: artifacts
  experiment_title: LogisticRegression_Mlops
  execution_name: mlops-diabetes
  model_registry_name: LogisticRegression-diabetes-prediction

reports:
   params: reports/params.json
   scores: reports/scores.json
