name: CI/CD Pipeline

# Trigger the workflow on push and pull requests to the 'Mlops-diabetes' branch
on:
  push:
    branches:
      - Mlops-diabetes
  pull_request:
    branches:
      - Mlops-diabetes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the correct branch (Mlops-diabetes)
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: Mlops-diabetes

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Step 3: Install dependencies (ensure Django, pytest, and other packages are included in requirements.txt)
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade setuptools
        pip install -r requirements.txt

    # Step 4: Run tests
    - name: Run tests
      run: |
        pytest tests/

    # Step 5: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t myapp .
